### ISSUE TITLE
Error in LDAP connection in "providers/ldap/util.py"

### ISSUE THREAD

**Issue by kastanas** [indico/flask-multipass#60]
In a new installation of [Newdle](https://github.com/indico/newdle), which uses Flask Multipass as an authentication backend, I observe the following error in the app when trying to connect to a OpenLDAP server in "providers/ldap/util.py":

```python
[2022-07-15 16:34:51,965] ERROR in app: Request failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/webargs/core.py", line 452, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/newdle/api.py", line 228, in users
    total, data = search_users(name, email, 10)
  File "/usr/local/lib/python3.10/site-packages/newdle/core/auth.py", line 59, in search_users
    identities, total = multipass.search_identities_ex(
  File "/usr/local/lib/python3.10/site-packages/flask_multipass/core.py", line 399, in search_identities_ex
    result = list(itertools.islice(result_iter, limit))
  File "/usr/local/lib/python3.10/site-packages/flask_multipass/providers/ldap/providers.py", line 194, in search_identities
    with ldap_context(self.ldap_settings):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/flask_multipass/providers/ldap/util.py", line 68, in ldap_context
    connection = ldap_connect(settings, use_cache=use_cache)
  File "/usr/local/lib/python3.10/site-packages/flask_multipass/providers/ldap/util.py", line 138, in ldap_connect
    ldap_connection.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_DEMAND if use_ldaps else ldap.OPT_X_TLS_NEVER)
AttributeError: module 'ldap' has no attribute 'OPT_X_TLS'
```

I have traced the error to using the latest version of `python-ldap`, version 3.4.2 (release 2022-07-06), which removes the deprecated option `OPT_X_TLS`, see the [changelog](https://github.com/python-ldap/python-ldap/blob/python-ldap-3.4.2/CHANGES).

Explicitly requiring at most python-ldap-3.4.1 makes everything work again.

**Comment by ThiefMaster** [comment]
A PR to remove this option (and if needed bump the minimum python-ldap version) would be appreciated! ;)

**Comment by kastanas** [comment]
Absolutely, I need to study a bit the way things are meant to be set up
after the deprecation and will submit it. :)
