### ISSUE TITLE
Flask-multipass ldap incompatible with python-ldap >=3.4.0

### ISSUE THREAD

**Issue by bpedersen2** [indico/flask-multipass#64]
The OPT_X_TLS flag has been deprecated in python-ldap 3.3.0 and removed in 3.4

2022-08-24 08:42:40,516  c21a2717f2244ef0  -       indico.flask - ERROR errors.py:98 -- module 'ldap' has no attribute 'OPT_X_TLS'

Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/flask/util.py", line 79, in wrapper
    return obj().process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/rh.py", line 281, in process
    res = self._do_process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/rh.py", line 252, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/auth/controllers.py", line 94, in _process
    response = multipass.handle_login_form(provider, form.data)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask_multipass/core.py", line 517, in handle_login_form
    response = provider.process_local_login(data)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask_multipass/providers/ldap/providers.py", line 71, in process_local_login
    with ldap_context(self.ldap_settings, use_cache=False):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask_multipass/providers/ldap/util.py", line 68, in ldap_context
    connection = ldap_connect(settings, use_cache=use_cache)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask_multipass/providers/ldap/util.py", line 138, in ldap_connect
    ldap_connection.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_DEMAND if use_ldaps else ldap.OPT_X_TLS_NEVER)
AttributeError: module 'ldap' has no attribute 'OPT_X_TLS'

**Comment by bpedersen2** [comment]
Already fixed im master
